In [35]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [36]:
# Load dataset
data_train  = pd.read_csv("citrus.csv")
data_train

name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [37]:
data_train.info

<bound method DataFrame.info of             name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]>

In [39]:
x = data_train.iloc[:,1:6].values
y = data_train.iloc[:,0].values

In [41]:
y

array(['orange', 'orange', 'orange', ..., 'grapefruit', 'grapefruit',
       'grapefruit'], dtype=object)

In [42]:
# Encoding
# x
# for i in range(coloumn):
#     x_train[: , i] = LabelEncoder().fit_transform(x_train[:,i])
# y
y                        = LabelEncoder().fit_transform(y)

In [43]:
# Normalize X
row,coloumn = x.shape
maxx = []
minn = []
for i in range(coloumn):
    maxx.append(np.max(x[:,i]))
    minn.append(np.min(x[:,i]))
print(maxx)
print(minn)

[16.45, 261.51, 192.0, 116.0, 56.0]
[2.96, 86.76, 115.0, 31.0, 2.0]


In [44]:
# Normalize X
for i in range(coloumn):  
    for j in range(row):
        x[j , i] = (x[j , i]- minn[i])/(maxx[i]-minn[i])

In [45]:
x

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [46]:
from sklearn.model_selection import  train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)


In [47]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [48]:
y_predd = knn.predict(x_test)
y_predd

array([0, 0, 0, ..., 0, 1, 0])

In [49]:
print(y_predd)

[0 0 0 ... 0 1 0]


In [52]:
from sklearn.metrics import classification_report, confusion_matrix

In [54]:
print(classification_report(y_test,y_predd))

              precision    recall  f1-score   support

           0       0.91      0.91      0.91       969
           1       0.92      0.91      0.91      1031

    accuracy                           0.91      2000
   macro avg       0.91      0.91      0.91      2000
weighted avg       0.91      0.91      0.91      2000



In [57]:
one = []
zero = []
for i in y_predd:
    if (i == 0):
        zero.append(i)
    elif(i == 1):
        one.append(i)

In [63]:
print(len(one))
print(len(zero))

1022
978


In [64]:
one = []
zero = []
for i in y_test:
    if (i == 0):
        zero.append(i)
    elif(i == 1):
        one.append(i)

In [65]:
print(len(one))
print(len(zero))

1031
969


In [71]:
#Save model
import pickle
knnModel = open('Model/Model_file', 'wb') 
pickle.dump(knn, knnModel)                      

In [ ]:
# load the model from disk
knn = pickle.load(open('Model/Model_file', 'rb'))
predict = knn.predict(X_test) 

In [60]:
# #------------------------------------------------------------------------------------------------------------
# #----------------------------Save Model----------------------------------------------------------------------
# import pickle
# with open('w_hidden1.ob', 'wb') as fp:
#     pickle.dump(w_hidden1, fp)
# with open('w_hidden2.ob', 'wb') as fp:
#     pickle.dump(w_hidden2, fp)
# with open('w_output.ob', 'wb') as fp:
#     pickle.dump(w_output, fp)
# with open('b_hidden1.ob', 'wb') as fp:
#     pickle.dump(b_hidden1, fp)
# with open('b_hidden2.ob', 'wb') as fp:
#     pickle.dump(b_hidden2, fp)
# with open('b_output.ob', 'wb') as fp:
#     pickle.dump(b_output, fp)

In [69]:
# #-------------------------------------------------------------------------------------------------------------
# #-------------------------------------Run from this-----------------------------------------------------------
# with open ('w_hidden1.ob', 'rb') as fp:
#     w_hidden1 = pickle.load(fp)
# with open ('w_hidden2.ob', 'rb') as fp:
#     w_hidden2 = pickle.load(fp)
# with open ('w_output.ob', 'rb') as fp:
#     w_output  = pickle.load(fp)
# with open ('b_hidden1.ob', 'rb') as fp:
#     b_hidden1 = pickle.load(fp)
# with open ('b_hidden2.ob', 'rb') as fp:
#     b_hidden2 = pickle.load(fp)
# with open ('b_output.ob', 'rb') as fp:
#     b_output  = pickle.load(fp)

In [40]:
# from tkinter import *
# from tkinter.ttk import Combobox
# from tkinter import messagebox


# class Test:
#     def __init__(self, tk):
#         self.var = StringVar()
#         self.data = (0, 1)
#         self.lb0 = Label(tk,  text = 'MULTILAYER PERCEPTRON PREDIKSI KESELAMATAN PENUMPANG TITANIC',
#                          font = ("Times",12)).place(x=15,y=0)
#         self.lb1 = Label(tk,  text = 'Sex',font = ("Times",9)).place(x=5,y=50)
#         self.lb2 = Label(tk,  text = 'Age',font = ("Times",9)).place(x=5,y=75)
#         self.lb3 = Label(tk,  text = 'SibSp',font = ("Times",9)).place(x=5,y=100)
#         self.lb4 = Label(tk,  text = 'Parch',font = ("Times",9)).place(x=5,y=125)
#         self.lb5 = Label(tk,  text = 'Fare',font = ("Times",9)).place(x=5,y=150)
#         self.lb6 = Label(tk,  text = 'Embarked',font = ("Times",9)).place(x=5,y=175)
#         #---------------------------------------------------------------------------------------------
#         self.cb1 = Combobox(tk, values=self.data,font = ("Times",9), width=17)
#         self.cb1.place(x=80, y=50)
#         self.e2  = Entry(tk,font = ("Times",9) )
#         self.e2.place(x=80,y=75)
#         self.e3  = Entry(tk,font = ("Times",9) )
#         self.e3.place(x=80,y=100)
#         self.e4  = Entry(tk,font = ("Times",9) )
#         self.e4.place(x=80,y=125)
#         self.e5  = Entry(tk,font = ("Times",9) )
#         self.e5.place(x=80,y=150)
#         self.e6  = Entry(tk,font = ("Times",9) )
#         self.e6.place(x=80,y=175)
#         #---------------------------------------------------------------------------------------------
#         self.b1  = Button(tk, text="Prediksi",font = ("Times",9), command=self.select).place(x=300, y=250, anchor=CENTER)
#         self.lb7 = Label(tk,  text = 'Hasil', font = ("Times",9))
#         self.lb7.place(x=300, y=300, anchor=CENTER)
        
#     def select(self):
#         data   = []
#         value1 = (float(self.cb1.get())-minn[0])/(maxx[0]-minn[0])
#         #messagebox.showinfo("Warn", "You selected " + value)
#         value2 = (float(self.e2.get())-minn[1])/(maxx[1]-minn[1])
#         value3 = (float(self.e3.get())-minn[2])/(maxx[2]-minn[2])
#         value4 = (float(self.e4.get())-minn[3])/(maxx[3]-minn[3])
#         value5 = (float(self.e5.get())-minn[4])/(maxx[4]-minn[4])
#         value6 = (float(self.e6.get())-minn[5])/(maxx[5]-minn[5])
#         data.append(value1)
#         data.append(value2)
#         data.append(value3)
#         data.append(value4)
#         data.append(value5)
#         data.append(value6)
#         HasilPredict = []
#         print(data)
#         for i in data:
#             # Hidden Layer1
#             o_hidden1 = np.matmul(data, w_hidden1) + b_hidden1
#             o_hidden1 = sig(o_hidden1)
#             # Hidden Layer2
#             o_hidden2 = np.matmul(o_hidden1, w_hidden2) + b_hidden2
#             o_hidden2 = sig(o_hidden2)
#             # Outpur Layer
#             o_output  = np.matmul(o_hidden2, w_output) + b_output
#             o_output  = sig(o_output)
#             HasilPredict.append(round(float(o_output)))
#         for i in HasilPredict:
#             if i == 1 :
#                 a = 'Selamat'
#             elif i == 0 :
#                 a = 'Tewas'
#         self.lb7.config(text=a)
# tk = Tk()
# tk.geometry("600x350")
# tk.title("MULTILAYER PERCEPTRON")
# tt = Test(tk)
# tk.mainloop()

[1.0, 0.7613636363636364, 0.6666666666666666, 0.8333333333333334, 0.97165991902834, 1.0]
[0.0, 0.7613636363636364, 0.6666666666666666, 0.8333333333333334, 0.97165991902834, 1.0]
[0.0, 0.5681818181818182, 0.6666666666666666, 0.8333333333333334, 0.97165991902834, 1.0]
[0.0, 0.5681818181818182, 0.16666666666666666, 0.8333333333333334, 0.97165991902834, 1.0]
[0.0, 0.5681818181818182, 0.16666666666666666, 0.6666666666666666, 0.97165991902834, 1.0]
[0.0, 0.5681818181818182, 0.16666666666666666, 0.6666666666666666, 0.6072874493927125, 1.0]
[0.0, 0.5681818181818182, 0.16666666666666666, 0.6666666666666666, 0.6072874493927125, 0.0]
[0.0, 0.5681818181818182, 0.16666666666666666, 0.6666666666666666, 0.46558704453441296, 0.0]
[0.0, 0.5681818181818182, 0.16666666666666666, 0.6666666666666666, 0.708502024291498, 0.0]
[0.0, 0.3409090909090909, 0.16666666666666666, 0.6666666666666666, 0.708502024291498, 0.0]
[0.0, 0.5227272727272727, 0.16666666666666666, 0.0, 0.708502024291498, 0.0]
[0.0, 0.5227272727

C:\Python3_7\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


[0.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[0.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[0.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[0.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[0.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[0.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[0.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[1.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[1.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[1.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.008097165991902834, 10.666666666666666]
[1.0, 0.3409090909090909, 0.0, 0.6666666666666666, 0.00809716599190283