In [75]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [76]:
# Load dataset
data_train  = pd.read_csv("citrus.csv")
data_train

name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [77]:
data_train.info

<bound method DataFrame.info of             name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]>

In [78]:
x = data_train.iloc[:,1:6].values
y = data_train.iloc[:,0].values

In [79]:
y

array(['orange', 'orange', 'orange', ..., 'grapefruit', 'grapefruit',
       'grapefruit'], dtype=object)

In [80]:
# Encoding
# x
# for i in range(coloumn):
#     x_train[: , i] = LabelEncoder().fit_transform(x_train[:,i])
# y
y                        = LabelEncoder().fit_transform(y)

In [81]:
# Normalize X
row,coloumn = x.shape
maxx = []
minn = []
for i in range(coloumn):
    maxx.append(np.max(x[:,i]))
    minn.append(np.min(x[:,i]))
print(maxx)
print(minn)

[16.45, 261.51, 192.0, 116.0, 56.0]
[2.96, 86.76, 115.0, 31.0, 2.0]


In [82]:
# Normalize X
for i in range(coloumn):  
    for j in range(row):
        x[j , i] = (x[j , i]- minn[i])/(maxx[i]-minn[i])

In [83]:
x

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [84]:
from sklearn.model_selection import  train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)


In [85]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [86]:
y_predd = knn.predict(x_test)
y_predd

array([1, 1, 0, ..., 1, 1, 0])

In [87]:
print(y_predd)

[1 1 0 ... 1 1 0]


In [88]:
from sklearn.metrics import classification_report, confusion_matrix

In [89]:
print(classification_report(y_test,y_predd))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      1025
           1       0.91      0.92      0.91       975

    accuracy                           0.92      2000
   macro avg       0.92      0.92      0.92      2000
weighted avg       0.92      0.92      0.92      2000



In [90]:
one = []
zero = []
for i in y_predd:
    if (i == 0):
        zero.append(i)
    elif(i == 1):
        one.append(i)

In [91]:
print(len(one))
print(len(zero))

980
1020


In [92]:
one = []
zero = []
for i in y_test:
    if (i == 0):
        zero.append(i)
    elif(i == 1):
        one.append(i)

In [93]:
print(len(one))
print(len(zero))

975
1025


In [94]:
#Save model
import pickle
knnModel = open('Model/Model_file', 'wb') 
pickle.dump(knn, knnModel)                      

In [95]:
# load the model from disk
knn = pickle.load(open('Model/Model_file', 'rb'))
predict = knn.predict(x) 